// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream():Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GenerateCode(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<string>;

export function GetConversations():Promise<string>;

export function GetPythonStatus():Promise<string>;

export function GetSettings():Promise<string>;

export function RebuildPythonRuntime():Promise<string>;

export function RunPythonScriptBackground(arg1:string):Promise<void>;

export function SaveConversation(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function StreamGenerateCode(arg1:string):Promise<void>;
