// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GenerateCode(arg1) {
  return window['go']['main']['App']['GenerateCode'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetPythonStatus() {
  return window['go']['main']['App']['GetPythonStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function RebuildPythonRuntime() {
  return window['go']['main']['App']['RebuildPythonRuntime']();
}

export function RunPythonScriptBackground(arg1) {
  return window['go']['main']['App']['RunPythonScriptBackground'](arg1);
}

export function SaveConversation(arg1, arg2) {
  return window['go']['main']['App']['SaveConversation'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StreamGenerateCode(arg1) {
  return window['go']['main']['App']['StreamGenerateCode'](arg1);
}
