// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelStream():Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GeogebraMessage(arg1:string):Promise<void>;

export function GeogebraValidateAndRegenerate(arg1:string):Promise<void>;

export function GetConversations():Promise<string>;

export function GetModels(arg1:Record<string, any>):Promise<Array<main.ModelInfo>>;

export function GetSettings():Promise<string>;

export function ListDirectory(arg1:string):Promise<string>;

export function SaveConversation(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function WriteLog(arg1:string,arg2:string):Promise<void>;
