// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GeogebraMessage(arg1) {
  return window['go']['main']['App']['GeogebraMessage'](arg1);
}

export function GeogebraValidateAndRegenerate(arg1) {
  return window['go']['main']['App']['GeogebraValidateAndRegenerate'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function SaveConversation(arg1, arg2) {
  return window['go']['main']['App']['SaveConversation'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2);
}
