// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateContent(arg1:string):Promise<Array<string>>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetPinyin(arg1:string):Promise<Array<string>>;

export function SaveAIConfig(arg1:main.AIConfig):Promise<boolean>;
