// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function AddRepoToStarGroup(arg1, arg2) {
  return window['go']['main']['App']['AddRepoToStarGroup'](arg1, arg2);
}

export function CreateStarGroup(arg1) {
  return window['go']['main']['App']['CreateStarGroup'](arg1);
}

export function DeleteStarGroup(arg1) {
  return window['go']['main']['App']['DeleteStarGroup'](arg1);
}

export function GetIssues(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIssues'](arg1, arg2, arg3);
}

export function GetMyRepos(arg1) {
  return window['go']['main']['App']['GetMyRepos'](arg1);
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetPRDiff(arg1, arg2) {
  return window['go']['main']['App']['GetPRDiff'](arg1, arg2);
}

export function GetPRFiles(arg1, arg2) {
  return window['go']['main']['App']['GetPRFiles'](arg1, arg2);
}

export function GetPullRequests(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPullRequests'](arg1, arg2, arg3);
}

export function GetRepoContents(arg1, arg2) {
  return window['go']['main']['App']['GetRepoContents'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStarGroups() {
  return window['go']['main']['App']['GetStarGroups']();
}

export function GetStarredRepos() {
  return window['go']['main']['App']['GetStarredRepos']();
}

export function GetWorkflowLogs(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflowLogs'](arg1, arg2);
}

export function GetWorkflowRunJobs(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflowRunJobs'](arg1, arg2);
}

export function GetWorkflowRuns(arg1) {
  return window['go']['main']['App']['GetWorkflowRuns'](arg1);
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['App']['RemoveBookmark'](arg1);
}

export function RemoveRepoFromStarGroup(arg1, arg2) {
  return window['go']['main']['App']['RemoveRepoFromStarGroup'](arg1, arg2);
}

export function RenameStarGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameStarGroup'](arg1, arg2);
}

export function ReorderBookmarks(arg1) {
  return window['go']['main']['App']['ReorderBookmarks'](arg1);
}

export function ReorderStarGroups(arg1) {
  return window['go']['main']['App']['ReorderStarGroups'](arg1);
}

export function SearchRepos(arg1) {
  return window['go']['main']['App']['SearchRepos'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function StarRepo(arg1) {
  return window['go']['main']['App']['StarRepo'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function SyncRepos(arg1) {
  return window['go']['main']['App']['SyncRepos'](arg1);
}

export function UnstarRepo(arg1) {
  return window['go']['main']['App']['UnstarRepo'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
