// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1:string):Promise<string>;

export function AddBookmark(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetIssues(arg1:string,arg2:string):Promise<string>;

export function GetMyRepos(arg1:string):Promise<string>;

export function GetNotifications():Promise<string>;

export function GetPRDiff(arg1:string,arg2:number):Promise<string>;

export function GetPRFiles(arg1:string,arg2:number):Promise<string>;

export function GetPullRequests(arg1:string,arg2:string):Promise<string>;

export function GetRepoContents(arg1:string,arg2:string):Promise<string>;

export function GetSettings():Promise<string>;

export function GetWorkflowLogs(arg1:string,arg2:number):Promise<string>;

export function GetWorkflowRunJobs(arg1:string,arg2:number):Promise<string>;

export function GetWorkflowRuns(arg1:string):Promise<string>;

export function MarkAllNotificationsRead():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function RemoveAccount(arg1:number):Promise<void>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function ReorderBookmarks(arg1:Array<string>):Promise<void>;

export function SearchRepos(arg1:string):Promise<string>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function SwitchAccount(arg1:number):Promise<void>;

export function UpdateSettings(arg1:string):Promise<void>;
