// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentMessage(arg1:string):Promise<void>;

export function CancelStream():Promise<void>;

export function DeleteFont(arg1:string):Promise<void>;

export function Generate(arg1:string):Promise<main.GenerateResult>;

export function GetFonts():Promise<Array<main.FontInfo>>;

export function GetModels(arg1:Record<string, any>):Promise<Array<main.ModelInfo>>;

export function GetSettings():Promise<string>;

export function SaveBase64Image(arg1:string,arg2:string):Promise<string>;

export function SaveFont(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;

export function WriteLog(arg1:string,arg2:string):Promise<void>;
