// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentMessage(arg1) {
  return window['go']['main']['App']['AgentMessage'](arg1);
}

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function DeleteFont(arg1) {
  return window['go']['main']['App']['DeleteFont'](arg1);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetFonts() {
  return window['go']['main']['App']['GetFonts']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveBase64Image(arg1, arg2) {
  return window['go']['main']['App']['SaveBase64Image'](arg1, arg2);
}

export function SaveFont(arg1, arg2) {
  return window['go']['main']['App']['SaveFont'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2);
}
