// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentMessage(arg1) {
  return window['go']['main']['App']['AgentMessage'](arg1);
}

export function AnalyzeColumns() {
  return window['go']['main']['App']['AnalyzeColumns']();
}

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function ExportCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2);
}

export function ExportExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportExcel'](arg1, arg2);
}

export function GetDataSummary() {
  return window['go']['main']['App']['GetDataSummary']();
}

export function GetDocType() {
  return window['go']['main']['App']['GetDocType']();
}

export function GetFileInfo() {
  return window['go']['main']['App']['GetFileInfo']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSheetData() {
  return window['go']['main']['App']['GetSheetData']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function LoadSheet(arg1) {
  return window['go']['main']['App']['LoadSheet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SampleData(arg1) {
  return window['go']['main']['App']['SampleData'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2);
}
