// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentMessage(arg1:string):Promise<void>;

export function AnalyzeColumns():Promise<Array<main.ColumnStats>>;

export function CancelStream():Promise<void>;

export function ExportCSV(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function ExportExcel(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function GetDataSummary():Promise<string>;

export function GetFileInfo():Promise<main.FileInfo>;

export function GetModels(arg1:Record<string, any>):Promise<Array<main.ModelInfo>>;

export function GetSettings():Promise<string>;

export function GetSheetData():Promise<main.SheetData>;

export function LoadFile(arg1:string):Promise<main.FileInfo>;

export function LoadSheet(arg1:string):Promise<main.SheetData>;

export function OpenFileDialog():Promise<main.FileInfo>;

export function SampleData(arg1:number):Promise<Array<any>>;

export function SaveSettings(arg1:string):Promise<void>;

export function WriteLog(arg1:string,arg2:string):Promise<void>;
