// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentMessage(arg1) {
  return window['go']['main']['App']['AgentMessage'](arg1);
}

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function DeleteMemoryEntry(arg1) {
  return window['go']['main']['App']['DeleteMemoryEntry'](arg1);
}

export function GetCompactionStatus() {
  return window['go']['main']['App']['GetCompactionStatus']();
}

export function GetContextStats() {
  return window['go']['main']['App']['GetContextStats']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMemory() {
  return window['go']['main']['App']['GetMemory']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveConversations(arg1) {
  return window['go']['main']['App']['SaveConversations'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoLearnEnabled(arg1) {
  return window['go']['main']['App']['SetAutoLearnEnabled'](arg1);
}

export function SetMemoryEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMemoryEntry'](arg1, arg2, arg3);
}

export function StreamMessage(arg1) {
  return window['go']['main']['App']['StreamMessage'](arg1);
}
