// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentMessage(arg1:string):Promise<void>;

export function CancelStream():Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteMemoryEntry(arg1:string):Promise<void>;

export function GetCompactionStatus():Promise<string>;

export function GetContextStats():Promise<string>;

export function GetConversations():Promise<string>;

export function GetMemory():Promise<string>;

export function GetModels(arg1:Record<string, any>):Promise<Array<main.ModelInfo>>;

export function GetSettings():Promise<string>;

export function ListDirectory(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveConversation(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SetAutoLearnEnabled(arg1:boolean):Promise<void>;

export function SetMemoryEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StreamMessage(arg1:Record<string, any>):Promise<void>;

export function WriteLog(arg1:string,arg2:string):Promise<void>;
